import { SUPPORTED_INDICATORS, CONTEXT_VARIABLES } from "./schema";

export interface LinterResult {
  valid: boolean;
  fixedStrategy: any;
  fixes: string[];
  errors: string[];
}

/**
 * Strategy Linter & Auto-Fixer
 * Ensures that the strategy generated by the Lab Assistant is engine-compatible.
 */
export function lintStrategy(strategy: any): LinterResult {
  const fixes: string[] = [];
  const errors: string[] = [];

  // 1. Normalize Root Structure (Handle both flat tool args and nested StrategyJSON)
  let indicators = strategy.indicators || strategy.setup?.indicators || {};
  let entryLogic = strategy.entryLogic || strategy.entry?.logic || "";
  let entryShortLogic = strategy.entryShortLogic || strategy.entry?.shortLogic || "";
  let exitLogic = strategy.exitLogic || strategy.exit?.logic || "";
  let exitShortLogic = strategy.exitShortLogic || strategy.exit?.shortLogic || "";

  // 2. Extract used tokens from all logic strings
  const usedTokens = new Set<string>();
  [entryLogic, entryShortLogic, exitLogic, exitShortLogic]
    .filter(Boolean)
    .forEach(logic => {
      extractTokens(logic).forEach(token => usedTokens.add(token));
    });

  // 3. Context Variables (built-in)
  const contextVarNames = new Set(CONTEXT_VARIABLES.map(v => v.name.toLowerCase()));
  const reservedKeywords = new Set(['TRUE', 'FALSE', 'AND', 'OR', 'NOT', 'CROSSOVER', 'CROSSUNDER']);

  // 4. Validate and Auto-Fix Indicator Definitions
  usedTokens.forEach(token => {
    // Skip numbers, reserved words, and context variables
    if (!isNaN(Number(token))) return;
    if (reservedKeywords.has(token.toUpperCase())) return;
    if (contextVarNames.has(token.toLowerCase())) return;

    // Handle _prev suffix (engine uses this for crossovers)
    const baseToken = token.endsWith('_prev') ? token.slice(0, -5) : token;
    
    // If it's a context variable with _prev (e.g., close_prev), it's valid
    if (contextVarNames.has(baseToken.toLowerCase())) return;

    if (!indicators[baseToken]) {
      const autoDef = attemptAutoFixIndicator(baseToken);
      if (autoDef) {
        indicators[baseToken] = autoDef;
        fixes.push(`Defined missing indicator: "${baseToken}" as ${autoDef.type}(${autoDef.period || ''})`);
      } else {
        errors.push(`Logic references undefined variable: "${baseToken}"`);
      }
    }
  });

  // 5. Cleanup Indicator Types
  Object.entries(indicators).forEach(([name, def]: [string, any]) => {
    const supported = SUPPORTED_INDICATORS.find(i => i.code === (def?.type || '').toUpperCase());
    if (!supported) {
      errors.push(`Indicator "${name}" uses unsupported type: "${def?.type}"`);
    } else if (def.type !== supported.code) {
      // Normalize casing (e.g., sma -> SMA)
      def.type = supported.code;
    }
  });

  // 6. Assemble Fixed Strategy (Nested structure for engine)
  const fixedStrategy = {
    ...strategy,
    setup: {
      ...strategy.setup,
      indicators
    },
    entry: {
      logic: entryLogic,
      shortLogic: entryShortLogic || undefined
    },
    exit: {
      logic: exitLogic,
      shortLogic: exitShortLogic || undefined,
      tpPct: strategy.tpPct ?? strategy.exit?.tpPct ?? 0.05,
      slPct: strategy.slPct ?? strategy.exit?.slPct ?? 0.02,
      tslPct: strategy.tslPct ?? strategy.exit?.tslPct,
      bePct: strategy.bePct ?? strategy.exit?.bePct,
      partialTps: strategy.partialTps ?? strategy.exit?.partialTps
    },
    startDate: strategy.startDate || strategy.setup?.startDate,
    endDate: strategy.endDate || strategy.setup?.endDate
  };

  return {
    valid: errors.length === 0,
    fixedStrategy,
    fixes,
    errors
  };
}

/**
 * Tokenizes a logic string to find potential variable/indicator names.
 */
function extractTokens(logic: string): string[] {
  // Matches words that aren't purely digits
  return (logic.match(/[A-Za-z_][A-Za-z0-9_]*/g) || []);
}

/**
 * Guesses indicator parameters based on common naming conventions.
 */
function attemptAutoFixIndicator(token: string): any {
  const patterns = [
    { regex: /^SMA_?(\d+)$/i, type: 'SMA' },
    { regex: /^EMA_?(\d+)$/i, type: 'EMA' },
    { regex: /^RSI_?(\d+)$/i, type: 'RSI' },
    { regex: /^HMA_?(\d+)$/i, type: 'HMA' },
    { regex: /^WMA_?(\d+)$/i, type: 'WMA' },
    { regex: /^ATR_?(\d+)$/i, type: 'ATR' },
    { regex: /^BB_?(\d+)$/i, type: 'BB' },
  ];

  for (const p of patterns) {
    const match = token.match(p.regex);
    if (match) {
      return { type: p.type, period: parseInt(match[1]) };
    }
  }

  // Fallbacks for bare names
  if (/^RSI$/i.test(token)) return { type: 'RSI', period: 14 };
  if (/^SMA$/i.test(token)) return { type: 'SMA', period: 50 };
  if (/^EMA$/i.test(token)) return { type: 'EMA', period: 20 };
  if (/^VWAP$/i.test(token)) return { type: 'VWAP' };
  if (/^OBV$/i.test(token)) return { type: 'OBV' };

  return null;
}
